import { UserScriptDivisionData } from '../../../src/topic/Heraldry/types';

export const urls: {
  unitBySource: {
    [source: string]: UserScriptDivisionData,
  },
} = {
  unitBySource: {},
};

urls.unitBySource['https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark'] = [
  {
      locationName: 'Albertslund Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Albertslund_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Albertslund_Kommune_coa.svg/105px-Albertslund_Kommune_coa.svg.png',
      description: 'Albertslund Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Allerød Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Aller%C3%B8d_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Aller%C3%B8d_Kommune_shield.png/97px-Aller%C3%B8d_Kommune_shield.png',
      description: 'Allerød Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Ballerup Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Ballerup_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Ballerup_Kommune_shield.png/104px-Ballerup_Kommune_shield.png',
      description: 'Ballerup Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Bornholms Regionskommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Bornholms_Regionskommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Bornholms_regionskommune_coa.svg/98px-Bornholms_regionskommune_coa.svg.png',
      description: 'Bornholms Regionskommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Brøndby Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Br%C3%B8ndby_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Br%C3%B8ndby_Kommune_shield.png/111px-Br%C3%B8ndby_Kommune_shield.png',
      description: 'Brøndby Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Dragør Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Drag%C3%B8r_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Drag%C3%B8r_Kommune_sjield.png/105px-Drag%C3%B8r_Kommune_sjield.png',
      description: 'Dragør Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Egedal Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Egedal_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Coat_of_arms_Egedal.svg/110px-Coat_of_arms_Egedal.svg.png',
      description: 'Egedal Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Fredensborg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Fredensborg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Fredensborg_Kommune_coa.svg/101px-Fredensborg_Kommune_coa.svg.png',
      description: 'Fredensborg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Frederiksberg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Frederiksberg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Frederiksberg_Kommune_coa.svg/101px-Frederiksberg_Kommune_coa.svg.png',
      description: 'Frederiksberg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Frederikssund Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Frederikssund_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Frederikssund_Kommune_coa.svg/104px-Frederikssund_Kommune_coa.svg.png',
      description: 'Frederikssund Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Furesø Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Fures%C3%B8_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Fures%C3%B8_Kommune_coa.svg/100px-Fures%C3%B8_Kommune_coa.svg.png',
      description: 'Furesø Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Gentofte Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Gentofte_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Gentofte_Kommune_coa.svg/90px-Gentofte_Kommune_coa.svg.png',
      description: 'Gentofte Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Gladsaxe Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Gladsaxe_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Gladsaxe_Kommune_shield.png/107px-Gladsaxe_Kommune_shield.png',
      description: 'Gladsaxe Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Glostrup Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Glostrup_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Glostrup_Kommune_coa.svg/108px-Glostrup_Kommune_coa.svg.png',
      description: 'Glostrup Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Gribskov Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Gribskov_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Gribskov_Kommune_shield.jpg/97px-Gribskov_Kommune_shield.jpg',
      description: 'Gribskov Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Halsnæs Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Halsn%C3%A6s_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Halsn%C3%A6s_Kommune_coa.svg/91px-Halsn%C3%A6s_Kommune_coa.svg.png',
      description: 'Halsnæs Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Helsingør Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Helsing%C3%B8r_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Coat_of_arms_of_Elsinore.svg/103px-Coat_of_arms_of_Elsinore.svg.png',
      description: 'Helsingør Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Herlev Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Herlev_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Herlev_Kommune_shield.png/111px-Herlev_Kommune_shield.png',
      description: 'Herlev Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Hillerød Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Hiller%C3%B8d_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Hiller%C3%B8d_Kommune_coa.svg/89px-Hiller%C3%B8d_Kommune_coa.svg.png',
      description: 'Hillerød Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Hvidovre Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Hvidovre_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Hvidovre_Kommune_shield.png/93px-Hvidovre_Kommune_shield.png',
      description: 'Hvidovre Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Høje-Taastrup Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/H%C3%B8je-Taastrup_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/H%C3%B8je-Taastrup_Kommune_shield.png/111px-H%C3%B8je-Taastrup_Kommune_shield.png',
      description: 'Høje-Taastrup Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Hørsholm Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/H%C3%B8rsholm_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Coat_of_arms_of_H%C3%B8rsholm.svg/105px-Coat_of_arms_of_H%C3%B8rsholm.svg.png',
      description: 'Hørsholm Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Ishøj Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Ish%C3%B8j_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Ishoj_Kommune_coa.svg/101px-Ishoj_Kommune_coa.svg.png',
      description: 'Ishøj Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Københavns Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/K%C3%B8benhavns_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Coat_of_arms_of_Copenhagen.svg/99px-Coat_of_arms_of_Copenhagen.svg.png',
      description: 'Københavns Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Lyngby-Taarbæk Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Lyngby-Taarb%C3%A6k_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Coats_of_arms_of_None.svg/100px-Coats_of_arms_of_None.svg.png',
      description: 'Lyngby-Taarbæk Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Rudersdal Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Rudersdal_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Rudersdal_Kommune_shield.jpg/93px-Rudersdal_Kommune_shield.jpg',
      description: 'Rudersdal Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Rødovre Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/R%C3%B8dovre_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/R%C3%B8dovre_Kommune_shield.png/110px-R%C3%B8dovre_Kommune_shield.png',
      description: 'Rødovre Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Tårnby Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/T%C3%A5rnby_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/T%C3%A5rnby_Kommune_shield.png/100px-T%C3%A5rnby_Kommune_shield.png',
      description: 'Tårnby Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Vallensbæk Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Vallensb%C3%A6k_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Vallensb%C3%A6k_Kommune_shield.png/109px-Vallensb%C3%A6k_Kommune_shield.png',
      description: 'Vallensbæk Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Hovedstaden',
    }, {
      locationName: 'Favrskov Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Favrskov_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Favrskov_kommune_coa.svg/90px-Favrskov_kommune_coa.svg.png',
      description: 'Favrskov Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Hedensted Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Hedensted_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Hedensted_Kommune_Skjold_SVG.svg/120px-Hedensted_Kommune_Skjold_SVG.svg.png',
      description: 'Hedensted Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Herning Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Herning_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Herning_Kommune_byv%C3%A5ben.svg/96px-Herning_Kommune_byv%C3%A5ben.svg.png',
      description: 'Herning Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Holstebro Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Holstebro_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Coat_of_arms_of_Holstebro.svg/105px-Coat_of_arms_of_Holstebro.svg.png',
      description: 'Holstebro Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Horsens Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Horsens_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Coat_of_arms_of_Horsens.svg/101px-Coat_of_arms_of_Horsens.svg.png',
      description: 'Horsens Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Ikast-Brande Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Ikast-Brande_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Ikast-Brande_Kommune_coa.svg/102px-Ikast-Brande_Kommune_coa.svg.png',
      description: 'Ikast-Brande Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Lemvig Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Lemvig_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Coat_of_arms_of_Lemvig.svg/100px-Coat_of_arms_of_Lemvig.svg.png',
      description: 'Lemvig Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Norddjurs Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Norddjurs_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Norddjurs_Kommune_Logo.svg/120px-Norddjurs_Kommune_Logo.svg.png',
      description: 'Norddjurs Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Odder Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Odder_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Odder_Kommune_coa.svg/106px-Odder_Kommune_coa.svg.png',
      description: 'Odder Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Randers Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Randers_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Coat_of_arms_of_Randers.svg/106px-Coat_of_arms_of_Randers.svg.png',
      description: 'Randers Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Ringkøbing-Skjern Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Ringk%C3%B8bing-Skjern_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Ringk%C3%B8bing-Skjern_Kommune_coa.svg/93px-Ringk%C3%B8bing-Skjern_Kommune_coa.svg.png',
      description: 'Ringkøbing-Skjern Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Samsø Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Sams%C3%B8_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Coat_of_arms_Sams%C3%B8.svg/114px-Coat_of_arms_Sams%C3%B8.svg.png',
      description: 'Samsø Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Silkeborg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Silkeborg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Coat_of_arms_of_Silkeborg.svg/94px-Coat_of_arms_of_Silkeborg.svg.png',
      description: 'Silkeborg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Skanderborg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Skanderborg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Coat_of_arms_of_Skanderborg.svg/95px-Coat_of_arms_of_Skanderborg.svg.png',
      description: 'Skanderborg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Skive Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Skive_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Coat_of_arms_of_Skive.svg/100px-Coat_of_arms_of_Skive.svg.png',
      description: 'Skive Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Struer Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Struer_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Coat_of_arms_of_Struer.svg/100px-Coat_of_arms_of_Struer.svg.png',
      description: 'Struer Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Syddjurs Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Syddjurs_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Coat_of_arms_Syddjurs.svg/114px-Coat_of_arms_Syddjurs.svg.png',
      description: 'Syddjurs Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Viborg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Viborg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Coat_of_arms_of_Viborg.svg/101px-Coat_of_arms_of_Viborg.svg.png',
      description: 'Viborg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Aarhus Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Aarhus_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Coat_of_arms_of_Aarhus.svg/101px-Coat_of_arms_of_Aarhus.svg.png',
      description: 'Aarhus Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Midtjylland',
    }, {
      locationName: 'Brønderslev Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Br%C3%B8nderslev_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Coat_of_arms_Br%C3%B8nderslev.svg/110px-Coat_of_arms_Br%C3%B8nderslev.svg.png',
      description: 'Brønderslev Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Frederikshavn Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Frederikshavn_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Frederikshavn_Kommune_Logo.svg/120px-Frederikshavn_Kommune_Logo.svg.png',
      description: 'Frederikshavn Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Hjørring Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Hj%C3%B8rring_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Coat_of_arms_of_Hj%C3%B8rring.svg/99px-Coat_of_arms_of_Hj%C3%B8rring.svg.png',
      description: 'Hjørring Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Jammerbugt Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Jammerbugt_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Jammerbugt_Kommune_coa.svg/114px-Jammerbugt_Kommune_coa.svg.png',
      description: 'Jammerbugt Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Læsø Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/L%C3%A6s%C3%B8_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Coats_of_arms_of_None.svg/100px-Coats_of_arms_of_None.svg.png',
      description: 'Læsø Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Mariagerfjord Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Mariagerfjord_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Mariagerfjord_Kommune_coa.svg/97px-Mariagerfjord_Kommune_coa.svg.png',
      description: 'Mariagerfjord Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Morsø Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Mors%C3%B8_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Mors%C3%B8_Kommune_coa.svg/100px-Mors%C3%B8_Kommune_coa.svg.png',
      description: 'Morsø Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Rebild Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Rebild_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Coats_of_arms_of_None.svg/100px-Coats_of_arms_of_None.svg.png',
      description: 'Rebild Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Thisted Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Thisted_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Coat_of_arms_of_Thisted.svg/93px-Coat_of_arms_of_Thisted.svg.png',
      description: 'Thisted Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Vesthimmerlands Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Vesthimmerlands_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Coats_of_arms_of_None.svg/100px-Coats_of_arms_of_None.svg.png',
      description: 'Vesthimmerlands Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Aalborg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Aalborg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Coat_of_arms_of_Aalborg.svg/114px-Coat_of_arms_of_Aalborg.svg.png',
      description: 'Aalborg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Nordjylland',
    }, {
      locationName: 'Faxe Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Faxe_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Faxe_Kommune_coa.svg/100px-Faxe_Kommune_coa.svg.png',
      description: 'Faxe Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Greve Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Greve_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Coat_of_arms_Greve.svg/114px-Coat_of_arms_Greve.svg.png',
      description: 'Greve Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Guldborgsund Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Guldborgsund_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Guldborgsund_Kommune_coa.svg/101px-Guldborgsund_Kommune_coa.svg.png',
      description: 'Guldborgsund Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Holbæk Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Holb%C3%A6k_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Coat_of_arms_of_Holb%C3%A6k.svg/112px-Coat_of_arms_of_Holb%C3%A6k.svg.png',
      description: 'Holbæk Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Kalundborg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Kalundborg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Kalundborg_Kommune_coa.svg/98px-Kalundborg_Kommune_coa.svg.png',
      description: 'Kalundborg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Køge Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/K%C3%B8ge_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/K%C3%B8ge_Kommune_coa.svg/95px-K%C3%B8ge_Kommune_coa.svg.png',
      description: 'Køge Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Lejre Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Lejre_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Lejre_Kommune_coa.svg/120px-Lejre_Kommune_coa.svg.png',
      description: 'Lejre Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Lolland Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Lolland_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Lolland_Kommune_coa.svg/94px-Lolland_Kommune_coa.svg.png',
      description: 'Lolland Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Næstved Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/N%C3%A6stved_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/N%C3%A6stved_Kommune_coa.svg/97px-N%C3%A6stved_Kommune_coa.svg.png',
      description: 'Næstved Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Odsherred Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Odsherred_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Odsherred_Kommune_coa.svg/95px-Odsherred_Kommune_coa.svg.png',
      description: 'Odsherred Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Ringsted Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Ringsted_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Coat_of_arms_of_Ringsted.svg/102px-Coat_of_arms_of_Ringsted.svg.png',
      description: 'Ringsted Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Roskilde Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Roskilde_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Coat_of_arms_of_Roskilde.svg/97px-Coat_of_arms_of_Roskilde.svg.png',
      description: 'Roskilde Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Slagelse Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Slagelse_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Slagelse_Kommune_coa.PNG/93px-Slagelse_Kommune_coa.PNG',
      description: 'Slagelse Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Solrød Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Solr%C3%B8d_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Solr%C3%B8d_Kommune_coa.svg/101px-Solr%C3%B8d_Kommune_coa.svg.png',
      description: 'Solrød Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Sorø Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Sor%C3%B8_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Soro_Kommunue_coa.svg/111px-Soro_Kommunue_coa.svg.png',
      description: 'Sorø Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Stevns Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Stevns_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Stevns_Kommune_coa.svg/120px-Stevns_Kommune_coa.svg.png',
      description: 'Stevns Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Vordingborg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Vordingborg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Vordingborg_Kommune_coa.PNG/88px-Vordingborg_Kommune_coa.PNG',
      description: 'Vordingborg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Sjælland',
    }, {
      locationName: 'Assens Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Assens_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Assens_Kommune_coa.svg/101px-Assens_Kommune_coa.svg.png',
      description: 'Assens Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Billund Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Billund_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Billund_Kommune_coa.svg/99px-Billund_Kommune_coa.svg.png',
      description: 'Billund Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Esbjerg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Esbjerg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Esbjerg_Kommune_coa.svg/100px-Esbjerg_Kommune_coa.svg.png',
      description: 'Esbjerg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Fanø Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Fan%C3%B8_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Fan%C3%B8_Kommune_Coat_of_Arms.png/107px-Fan%C3%B8_Kommune_Coat_of_Arms.png',
      description: 'Fanø Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Fredericia Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Fredericia_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Fredericia_Kommune_coa.svg/120px-Fredericia_Kommune_coa.svg.png',
      description: 'Fredericia Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Faaborg-Midtfyn Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Faaborg-Midtfyn_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Faaborg-Midtfyn_Kommune_coa.svg/88px-Faaborg-Midtfyn_Kommune_coa.svg.png',
      description: 'Faaborg-Midtfyn Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Haderslev Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Haderslev_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Haderslev_Kommune_coa.svg/96px-Haderslev_Kommune_coa.svg.png',
      description: 'Haderslev Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Kerteminde Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Kerteminde_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Coats_of_arms_of_None.svg/100px-Coats_of_arms_of_None.svg.png',
      description: 'Kerteminde Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Kolding Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Kolding_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Kolding_Kommune_coa.svg/91px-Kolding_Kommune_coa.svg.png',
      description: 'Kolding Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Langeland Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Langeland_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Langeland_Kommune_coa.svg/100px-Langeland_Kommune_coa.svg.png',
      description: 'Langeland Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Middelfart Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Middelfart_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Middelfart_Kommune_coa.svg/95px-Middelfart_Kommune_coa.svg.png',
      description: 'Middelfart Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Nordfyns Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Nordfyns_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Coat_of_arms_of_Bogense.svg/104px-Coat_of_arms_of_Bogense.svg.png',
      description: 'Nordfyns Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Nyborg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Nyborg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Nyborg_Kommune_coa.svg/93px-Nyborg_Kommune_coa.svg.png',
      description: 'Nyborg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Odense Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Odense_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Coat_of_arms_of_Odense.svg/112px-Coat_of_arms_of_Odense.svg.png',
      description: 'Odense Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Svendborg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Svendborg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_shield_of_Svendborg_Kommune.jpg/90px-The_shield_of_Svendborg_Kommune.jpg',
      description: 'Svendborg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Sønderborg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/S%C3%B8nderborg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Coat_of_arms_of_S%C3%B8nderborg.svg/97px-Coat_of_arms_of_S%C3%B8nderborg.svg.png',
      description: 'Sønderborg Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Tønder Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/T%C3%B8nder_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Coat_of_arms_of_T%C3%B8nder.svg/102px-Coat_of_arms_of_T%C3%B8nder.svg.png',
      description: 'Tønder Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Varde Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Varde_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Coat_of_arms_of_Varde.svg/107px-Coat_of_arms_of_Varde.svg.png',
      description: 'Varde Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Vejen Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Vejen_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Coats_of_arms_of_None.svg/100px-Coats_of_arms_of_None.svg.png',
      description: 'Vejen Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Vejle Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Vejle_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Vejle_Kommune_coa.svg/95px-Vejle_Kommune_coa.svg.png',
      description: 'Vejle Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Ærø Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/%C3%86r%C3%B8_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/%C3%86r%C3%B8_Kommune_coa.svg/102px-%C3%86r%C3%B8_Kommune_coa.svg.png',
      description: 'Ærø Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }, {
      locationName: 'Aabenraa Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Aabenraa_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Aabenraa_Kommune_coa.svg/97px-Aabenraa_Kommune_coa.svg.png',
      description: 'Aabenraa Kommune',
      type: ['kommune'],
      source: 'https://da.wikipedia.org/wiki/Kommunev%C3%A5bener_i_Danmark',
      sourceTitle: 'Kommunevåbener i Danmark | Region Syddanmark',
    }
]; 


urls.unitBySource['https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark'] = [
  {
      locationName: 'Bornholms Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Bornholms_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Bornholms_regionskommune_coa.svg/98px-Bornholms_regionskommune_coa.svg.png',
      description: 'Bornholms Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Frederiksberg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Frederiksberg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Frederiksberg_Kommune_coa.svg/101px-Frederiksberg_Kommune_coa.svg.png',
      description: 'Frederiksberg Kommune',
      type: ['formerKommune'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Frederiksborg Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Frederiksborg_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Frederiksborg_amt_coa.svg/112px-Frederiksborg_amt_coa.svg.png',
      description: 'Frederiksborg Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Fyns Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Fyns_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Fyns_amt_coa.svg/94px-Fyns_amt_coa.svg.png',
      description: 'Fyns Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Københavns Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/K%C3%B8benhavns_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/K%C3%B8benhavns_amt_coa.svg/101px-K%C3%B8benhavns_amt_coa.svg.png',
      description: 'Københavns Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Københavns Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/K%C3%B8benhavns_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Coat_of_arms_of_Copenhagen.svg/99px-Coat_of_arms_of_Copenhagen.svg.png',
      description: 'Københavns Kommune',
      type: ['formerKommune'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Nordjyllands Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Nordjyllands_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Nordjyllands_amt_coa.svg/97px-Nordjyllands_amt_coa.svg.png',
      description: 'Nordjyllands Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Ribe Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Ribe_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Ribe_amt_coa.svg/94px-Ribe_amt_coa.svg.png',
      description: 'Ribe Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Ringkjøbing Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Ringkj%C3%B8bing_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Ringkj%C3%B8bing_amt_coa.svg/101px-Ringkj%C3%B8bing_amt_coa.svg.png',
      description: 'Ringkjøbing Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Roskilde Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Roskilde_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Roskilde_amt_coa.svg/94px-Roskilde_amt_coa.svg.png',
      description: 'Roskilde Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Storstrøms amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Storstr%C3%B8ms_amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Storstr%C3%B8ms_amt_coa.svg/106px-Storstr%C3%B8ms_amt_coa.svg.png',
      description: 'Storstrøms amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Sønderjyllands amt',
      locationUrl: 'https://da.wikipedia.org/wiki/S%C3%B8nderjyllands_amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/S%C3%B8nderjyllands_amt_coa.svg/91px-S%C3%B8nderjyllands_amt_coa.svg.png',
      description: 'Sønderjyllands amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Vejle Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Vejle_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Vejle_amt_coa.svg/94px-Vejle_amt_coa.svg.png',
      description: 'Vejle Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Vestsjællands Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Vestsj%C3%A6llands_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Vestsj%C3%A6llands_amt_coa.svg/90px-Vestsj%C3%A6llands_amt_coa.svg.png',
      description: 'Vestsjællands Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Viborg Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Viborg_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Viborg_amt_coa.svg/95px-Viborg_amt_coa.svg.png',
      description: 'Viborg Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Århus Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/%C3%85rhus_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/%C3%85rhus_amt_coa.svg/98px-%C3%85rhus_amt_coa.svg.png',
      description: 'Århus Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener 1970-2006',
    }, {
      locationName: 'Assens Amtsrådskreds',
      locationUrl: 'https://da.wikipedia.org/wiki/Assens_Amt#Assens_Amtsr%C3%A5dskreds_1842-1970',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Coat_of_arms_of_Assens_County_Municipality.svg/110px-Coat_of_arms_of_Assens_County_Municipality.svg.png',
      description: 'Assens Amtsrådskreds',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Bornholms Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Bornholms_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Coat_of_arms_of_Bornholm.svg/113px-Coat_of_arms_of_Bornholm.svg.png',
      description: 'Bornholms Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Frederiksberg Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/Frederiksberg_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Coat_of_arms_of_Frederiksberg.svg/102px-Coat_of_arms_of_Frederiksberg.svg.png',
      description: 'Frederiksberg Kommune',
      type: ['formerKommune'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Frederiksborg Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Frederiksborg_Amt_(f%C3%B8r_1970)',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Coat_of_arms_of_Frederiksborg_County.svg/111px-Coat_of_arms_of_Frederiksborg_County.svg.png',
      description: 'Frederiksborg Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Færø Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/F%C3%A6r%C3%B8ernes_historie#Selvst%C3%A6ndigt_F%C3%A6r%C3%B8_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Coat_of_arms_of_the_Faroe_Islands.svg/102px-Coat_of_arms_of_the_Faroe_Islands.svg.png',
      description: 'Færø Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Haderslev Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Haderslev_Amt_(f%C3%B8r_1970)',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Coats_of_arms_of_None.svg/100px-Coats_of_arms_of_None.svg.png',
      description: 'Haderslev Amt Førte ikke våben',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Hjørring Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Hj%C3%B8rring_Amt_(f%C3%B8r_1970)',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Coat_of_arms_of_Hj%C3%B8rring_County.svg/113px-Coat_of_arms_of_Hj%C3%B8rring_County.svg.png',
      description: 'Hjørring Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Holbæk Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Holb%C3%A6k_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Coat_of_arms_of_Holb%C3%A6k_County.svg/98px-Coat_of_arms_of_Holb%C3%A6k_County.svg.png',
      description: 'Holbæk Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Københavns Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/K%C3%B8benhavns_Amt_(f%C3%B8r_1970)',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Coat_of_arms_of_Copenhagen_County.svg/100px-Coat_of_arms_of_Copenhagen_County.svg.png',
      description: 'Københavns Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Københavns Kommune',
      locationUrl: 'https://da.wikipedia.org/wiki/K%C3%B8benhavns_Kommune',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Coat_of_arms_of_Copenhagen.svg/99px-Coat_of_arms_of_Copenhagen.svg.png',
      description: 'Københavns Kommune',
      type: ['formerKommune'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Maribo Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Maribo_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Coat_of_arms_of_Maribo_County.svg/111px-Coat_of_arms_of_Maribo_County.svg.png',
      description: 'Maribo Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Odense Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Odense_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Coat_of_arms_of_Odense_County.svg/110px-Coat_of_arms_of_Odense_County.svg.png',
      description: 'Odense Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Præstø Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Pr%C3%A6st%C3%B8_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Coat_of_arms_of_Pr%C3%A6st%C3%B8_County.svg/113px-Coat_of_arms_of_Pr%C3%A6st%C3%B8_County.svg.png',
      description: 'Præstø Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Randers Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Randers_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Coat_of_arms_of_Randers_County.svg/96px-Coat_of_arms_of_Randers_County.svg.png',
      description: 'Randers Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Ribe Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Ribe_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Coat_of_arms_of_Ribe_County.svg/95px-Coat_of_arms_of_Ribe_County.svg.png',
      description: 'Ribe Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Ringkøbing Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Ringk%C3%B8bing_Amt_(f%C3%B8r_1970)',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Coat_of_arms_of_Ringk%C3%B8bing_County.svg/100px-Coat_of_arms_of_Ringk%C3%B8bing_County.svg.png',
      description: 'Ringkøbing Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Roskilde Amtsådskreds',
      locationUrl: 'https://da.wikipedia.org/wiki/Roskilde_Amt_(f%C3%B8r_1970)',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Coat_of_arms_of_Roskilde_County.svg/100px-Coat_of_arms_of_Roskilde_County.svg.png',
      description: 'Roskilde Amtsådskreds',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Skanderborg Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Skanderborg_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Coat_of_arms_of_Skanderborg_County.svg/111px-Coat_of_arms_of_Skanderborg_County.svg.png',
      description: 'Skanderborg Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Sorø Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Sor%C3%B8_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Coat_of_arms_of_Sor%C3%B8_County.svg/108px-Coat_of_arms_of_Sor%C3%B8_County.svg.png',
      description: 'Sorø Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Svendborg Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Svendborg_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Coat_of_arms_of_Svendborg_County.svg/109px-Coat_of_arms_of_Svendborg_County.svg.png',
      description: 'Svendborg Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Sønderborg Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/S%C3%B8nderborg_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Coat_of_arms_of_S%C3%B8nderborg_County.svg/94px-Coat_of_arms_of_S%C3%B8nderborg_County.svg.png',
      description: 'Sønderborg Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Thisted Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Thisted_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Coat_of_arms_of_Thisted_County.svg/100px-Coat_of_arms_of_Thisted_County.svg.png',
      description: 'Thisted Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Tønder Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/T%C3%B8nder_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Coat_of_arms_of_T%C3%B8nder_County.svg/109px-Coat_of_arms_of_T%C3%B8nder_County.svg.png',
      description: 'Tønder Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Vejle Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Vejle_Amt_(f%C3%B8r_1970)',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Coat_of_arms_of_Vejle_County.svg/101px-Coat_of_arms_of_Vejle_County.svg.png',
      description: 'Vejle Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Viborg Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Viborg_Amt_(f%C3%B8r_1970)',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Coat_of_arms_of_Viborg_County_%281959-1977%29.svg/111px-Coat_of_arms_of_Viborg_County_%281959-1977%29.svg.png',
      description: 'Viborg Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Aabenraa Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Aabenraa_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Coat_of_arms_of_Aabenraa_County.svg/95px-Coat_of_arms_of_Aabenraa_County.svg.png',
      description: 'Aabenraa Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Aalborg Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/Aalborg_Amt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Coat_of_arms_of_Aalborg_County.svg/96px-Coat_of_arms_of_Aalborg_County.svg.png',
      description: 'Aalborg Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }, {
      locationName: 'Århus Amt',
      locationUrl: 'https://da.wikipedia.org/wiki/%C3%85rhus_Amt_(f%C3%B8r_1970)',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Coat_of_arms_of_%C3%85rhus_County%281959-1970%29.svg/98px-Coat_of_arms_of_%C3%85rhus_County%281959-1970%29.svg.png',
      description: 'Århus Amt',
      type: ['formerAmt'],
      source: 'https://da.wikipedia.org/wiki/Amtsv%C3%A5bener_i_Danmark',
      sourceTitle: 'Amtsvåbener i Danmark | Amtsvåbener før 1970',
    }
]; 
