import { CountryOverridesInput } from "../utils/helpers/data/overrides/types";

export const overrides: CountryOverridesInput = {
  imageUrlByWikipediaUrlThumbnail: {
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Zevenhuizen_Moerkapelle_wapen.svg/langnl-330px-Zevenhuizen_Moerkapelle_wapen.svg.png":
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Zevenhuizen_Moerkapelle_wapen.svg/1920px-Zevenhuizen_Moerkapelle_wapen.svg.png",
  },
  locationsByTitle: {
    "Wapen van Schuddebeurs en Simonshaven": {
      name: "Geervliet",
      coordinates: {
        lat: 51.86111111,
        lon: 4.26222222,
      },
    },
    "Wapen van Overschie": {
      name: "Geervliet",
      coordinates: {
        lat: 51.935,
        lon: 4.429444,
      },
    },
  },
  locationPageByTitle: {
    "Wapen van Herwen en Aerdt": "Zevenaar (gemeente)",
    "Wapen van Zegwaart": "Zoetermeer",
    "Wapen van Valkenisse (Zuid-Beveland)": "Reimerswaal (gemeente)",
    "Wapen van Jabeek": "Beekdaelen",
    "Wapen van Heille": "Sluis (gemeente)",
    "Wapen van Limburg (Nederland)": "Limburg (Nederlandse provincie)",
    "Wapen van Broeksittard": "Sittard-Geleen",
    "Wapen van Oosterbroek": "Menterwolde",
    "Wapen van Sloten (Friesland)": "Sloten (Friesland)",
    "Wapen van Melick en Herkenbosch": "Herkenbosch",
    "Wapen van Kessel (Limburg)": "Kessel (Limburg)",
    "Wapen van Nieuwveen": "Nieuwveen (Nieuwkoop)",
    "Wapen van Nieuwland": "Nieuwland (Vijfheerenlanden)",
    "Wapen van Niemandsvriend": "Tolhuis Niemandsvriend",
    "Wapen van de heerlijkheid Nederslingeland": "Molenlanden",
    "Wapen van Lange Ruige Weide": "Bodegraven-Reeuwijk",
    "Wapen van IJsselmonde": "IJsselmonde (stadsdeel)",
    "Wapen van Heer Oudelands Ambacht": "Zwijndrecht (Nederland)",
    "Wapen van Hazerswoude": "Hazerswoude-Dorp",
    "Wapen van Delfshaven": "Delfshaven (stadsdeel)",
    "Wapen van Zwake": "'s-Gravenpolder (dorp)",
    "Wapen van Valkenisse (Zuid-Beveland)": "Valkenisse (Zuid-Beveland)",
    "Wapen van Valkenisse (Walcheren)": "Valkenisse (Walcheren)",
    "Wapen van Sinoutskerke en Baarsdorp": "Borsele (gemeente)",
    "Wapen van Serooskerke (Veere)": "Serooskerke (Veere)",
    "Wapen van Serooskerke (Schouwen-Duiveland)":
      "Serooskerke (Schouwen-Duiveland)",
    "Wapen van Overslag": "Overslag (Zeeland)",
    "Wapen van Oost- en West-Souburg": "Oost-Souburg",
    "Wapen van Nieuwerkerke": "Nieuwerkerke (Schouwen-Duiveland)",
    "Wapen van Nieuwerkerk (Duiveland)": "Nieuwerkerk (Zeeland)",
    "Wapen van Maire": "Zeeland (provincie)",
    "Wapen van Koudekerke": "Koudekerke (Walcheren)",
    "Wapen van Hontenisse": "Vogelwaarde",
    "Wapen van Hoek": "Hoek (Terneuzen)",
    "Wapen van Driewegen": "Driewegen (Borsele)",
    "Wapen van Botland": "Schouwen-Duiveland",
    "Wapen van Aardenburg": "Aardenburg (stad)",
    "Wapen van Zuid-Polsbroek": "Polsbroek",
    "Wapen van Westbroek": "Westbroek (Utrecht)",
    "Wapen van Vreeswijk": "Vreeswijk (wijk)",
    "Wapen van Schalkwijk": "Schalkwijk (Houten)",
    "Wapen van Oudenrijn": "Oudenrijn (Utrecht)",
    "Wapen van Noord-Polsbroek": "Polsbroek",
    "Wapen van Breukelen-Sint Pieters": "Breukeleveen",
    "Wapen van Breukelen-Nijenrode": "Utrecht (provincie)",
    "Wapen van Breukelen": "Breukelen (Utrecht)",
    "Wapen van Stad Ommen": "Overijssel",
    "Wapen van Stad Hardenberg": "Hardenberg (gemeente)",
    "Wapen van Den Ham": "Den Ham (Overijssel)",
    "Wapen van Zwaag": "Zwaag (Hoorn)",
    "Wapen van Sloten (Noord-Holland)": "Sloten (plaats in Noord-Holland)",
    "Wapen van Marken": "Marken (Waterland)",
    "Wapen van Bijlmermeer": "Amsterdam",
    "Wapen van Willemstad": "Willemstad (Noord-Brabant)",
    "Wapen van Veen (Aalburg)": "Aalburg",
    "Wapen van Strijp": "Strijp (Eindhoven)",
    "Wapen van Stratum": "Stratum (Eindhoven)",
    "Wapen van Soerendonk, Sterksel en Gastel": "Soerendonk en Sterksel",
    "Wapen van Roosendaal en Nispen": "Roosendaal (gemeente)",
    "Wapen van Putte (Woensdrecht)": "Woensdrecht (gemeente)",
    "Wapen van Oud en Nieuw Gastel": "Nieuw Gastel",
    "Wapen van Oploo, Sint Anthonis en Ledeacker": "Sint Anthonis en Ledeacker",
    "Wapen van Oijen en Teeffelen": "Teeffelen",
    "Wapen van Nuenen en Gerwen": "Nuenen, Gerwen en Nederwetten",
    "Wapen van Nieuw-Ginneken": "Ginneken",
    "Wapen van Nederwetten en Eckart": "Nederwetten",
    "Wapen van Megen, Haren en Macharen": "Haren en Macharen",
    "Wapen van Meeuwen": "Meeuwen (Altena)",
    "Wapen van Maashees en Overloon": "Overloon",
    "Wapen van Linden (Noord-Brabant)": "Linden (Noord-Brabant)",
    "Wapen van Kessel (Noord-Brabant)": "Kessel (Noord-Brabant)",
    "Wapen van Hooge en Lage Zwaluwe": "Zevenbergen (Moerdijk)",
    "Wapen van Hooge en Lage Mierde": "Lage Mierde",
    "Wapen van Hoeven": "Hoeven (Halderberge)",
    "Wapen van Ginneken en Bavel": "Bavel",
    "Wapen van Giessen (Noord-Brabant)": "Giessen (Noord-Brabant)",
    "Wapen van Fijnaart en Heijningen": "Heijningen",
    "Wapen van Esch (Boxtel)": "Esch (Boxtel)",
    "Wapen van Erp (Meierijstad)": "Erp (Meierijstad)",
    "Wapen van Emmikhoven en Waardhuizen": "Waardhuizen (plaats)",
    "Wapen van Duizel en Steensel": "Steensel",
    "Wapen van Diessen (Noord-Brabant)": "Diessen (Noord-Brabant)",
    "Wapen van Deurne en Liessel": "Deurne (gemeente)",
    "Wapen van De Werken en Sleeuwijk": "Werkendam (gemeente)",
    "Wapen van Capelle (Noord-Brabant)": "Capelle (Noord-Brabant)",
    "Wapen van Berghem": "Berghem (Noord-Brabant)",
    "Wapen van Beers (Noord-Brabant)": "Beers (Noord-Brabant)",
    "Wapen van Alem, Maren en Kessel": "Kessel (Noord-Brabant)",
    "Wapen van Aalst (Noord-Brabant)": "Aalst (Noord-Brabant)",
    "Wapen van Hoeksche Waard (gemeente)": "Hoeksche Waard (eiland)",
    "Wapen van Obbicht en Papenhoven": "Papenhoven",
    "Wapen van Sint Pieter": "Sint Pieter (Maastricht)",
    "Wapen van Roosteren": "Roosteren (Limburg)",
    "Wapen van Made en Drimmelen": "Drimmelen (gemeente)",
    "Wapen van Echt": "Echt (Limburg)",
    "Wapen van Berg en Terblijt": "Terblijt",
    "Wapen van Borne": "Borne (Overijssel)",
    "Wapen van 't Zandt": "'t Zandt (Groningen)",
    "Wapen van Wedde": "Wedde (Westerwolde)",
    "Wapen van Oldehove": "Oldehove (Groningen)",
    "Wapen van Bergen (Noord-Holland)": "Bergen (gemeente in Noord-Holland)",
    "Wapen van Maashorst": "Landerd",
    "Wapen van Lienden": "Lienden (Buren)",
    "Wapen van Keppel": "Gelderland",
    "Wapen van Est en Opijnen": "Gelderland",
    "Wapen van Wymbritseradeel": "Sneek (stad)",
    "Wapen van Aalst (Zaltbommel)": "Aalst (Zaltbommel)",
    "Wapen van Niftrik": "Niftrik (plaats)",
  },
};
