import { UserScriptDivisionData } from '../../../../src/topic/Heraldry/types';

export const urls: {
  unitBySource: {
    [source: string]: UserScriptDivisionData[],
  },
} = {
  unitBySource: {},
};


urls.unitBySource['https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg'] = [
  {
      locationName: 'Kleines Staatswappen',
      locationUrl: 'https://de.wikipedia.org/wiki/Landeswappen_Hamburgs#Kleines_Staatswappen',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/DEU_Hamburg_COA.svg/86px-DEU_Hamburg_COA.svg.png',
      description: 'Kleines Staatswappen',
      type: ['land'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Landeswappen',
    }, {
      locationName: 'Mittleres Staatswappen',
      locationUrl: 'https://de.wikipedia.org/wiki/Landeswappen_Hamburgs#Gro%C3%9Fes_Staatswappen_und_Logo',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Middle_Coat_of_arms_of_Hamburg.svg/116px-Middle_Coat_of_arms_of_Hamburg.svg.png',
      description: 'Mittleres Staatswappen',
      type: ['land'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Landeswappen',
    }, {
      locationName: 'Großes Staatswappen',
      locationUrl: 'https://de.wikipedia.org/wiki/Landeswappen_Hamburgs#Gro%C3%9Fes_Staatswappen_und_Logo',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Wappen_der_Hamburgischen_B%C3%BCrgerschaft.svg/120px-Wappen_der_Hamburgischen_B%C3%BCrgerschaft.svg.png',
      description: 'Großes Staatswappen',
      type: ['land'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Landeswappen',
    }, {
      locationName: '',
      locationUrl: '',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Wappen-Altona.svg/97px-Wappen-Altona.svg.png',
      description: 'Aktuelles Wappen bzw. Logo',
      type: ['formerBezirke'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Bezirke (auch historische)',
    }, {
      locationName: '',
      locationUrl: '',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/DEU_Altona_COA.svg/105px-DEU_Altona_COA.svg.png',
      description: 'Wappen bis 1937',
      type: ['formerBezirke'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Bezirke (auch historische)',
    }, {
      locationName: '',
      locationUrl: '',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wappen_Hamburg-Altona.png/103px-Wappen_Hamburg-Altona.png',
      description: 'Frühere Variante',
      type: ['formerBezirke'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Bezirke (auch historische)',
    }, {
      locationName: '',
      locationUrl: '',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Fensterbild_mit_Wappen_von_Hamburg_Altona.jpg/108px-Fensterbild_mit_Wappen_von_Hamburg_Altona.jpg',
      description: 'Wappen als Fensterbild',
      type: ['formerBezirke'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Bezirke (auch historische)',
    }, {
      locationName: 'Bergstedt',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Bergstedt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Wappen_Bergstedt.png/107px-Wappen_Bergstedt.png',
      description: 'Bergstedt',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Bramfeld',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Bramfeld',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Wappen_Bramfeld.png/120px-Wappen_Bramfeld.png',
      description: '↑ Bramfelds Wappen. Stadtteilarchiv Bramfeld, abgerufen am 22. März 2024. Bramfeld[3]',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Eidelstedt',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Eidelstedt#Wappen',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/de/thumb/e/eb/Wappen_eidelstedt_solo_rgb_trans.png/105px-Wappen_eidelstedt_solo_rgb_trans.png',
      description: 'Eidelstedt',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Langenhorn',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Langenhorn',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Coa_hh-langenhorn.svg/100px-Coa_hh-langenhorn.svg.png',
      description: 'Langenhorn',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Lurup',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Lurup',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Wappen_Lurup.png/91px-Wappen_Lurup.png',
      description: '↑ neu.atdotde.de (PDF; 12 MB) Lurup[4]',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Ochsenwerder',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Ochsenwerder',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Wappen_Ochsenwerder.png/98px-Wappen_Ochsenwerder.png',
      description: 'Ochsenwerder',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Ottensen',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Ottensen',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Wappen_Ottensen.png/92px-Wappen_Ottensen.png',
      description: 'Ottensen',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Wellingsbüttel',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Wellingsb%C3%BCttel',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Wappen_Wellingsbuettel.png/108px-Wappen_Wellingsbuettel.png',
      description: 'Wellingsbüttel',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Wilhelmsburg',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Wilhelmsburg',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Wappen_Hamburg-Wilhelmsburg.png/115px-Wappen_Hamburg-Wilhelmsburg.png',
      description: 'Wilhelmsburg',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }
]; 
