import { UserScriptDivisionData } from '../../../../src/topic/Heraldry/types';

export const urls: {
  unitBySource: {
    [source: string]: UserScriptDivisionData[],
  },
} = {
  unitBySource: {},
};


urls.unitBySource['https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg'] = [
  {
      locationName: 'Kleines Staatswappen',
      locationUrl: 'https://de.wikipedia.org/wiki/Landeswappen_Hamburgs#Kleines_Staatswappen',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/DEU_Hamburg_COA.svg/86px-DEU_Hamburg_COA.svg.png',
      description: 'Kleines Staatswappen |||| Das Wappenbild des kleinen Staatswappens, welches heute als Landeswappen und staatliches Hoheitszeichen von den hamburgischen Behörden und Anstalten des öffentlichen Rechts verwendet wird, ist in den wesentlichen Grundzügen seit Beginn unverändert.',
      type: ['land'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Landeswappen',
    }, {
      locationName: 'Mittleres Staatswappen',
      locationUrl: 'https://de.wikipedia.org/wiki/Landeswappen_Hamburgs#Gro%C3%9Fes_Staatswappen_und_Logo',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Middle_Coat_of_arms_of_Hamburg.svg/116px-Middle_Coat_of_arms_of_Hamburg.svg.png',
      description: 'Mittleres Staatswappen |||| Das große Staatswappen darf nur von der Bürgerschaft, vom Senat, dem Hamburgischen Verfassungsgericht, dem Hanseatischen Oberlandesgericht sowie dem Landgericht Hamburg geführt werden. Es zeigt den roten Wappenschild mit weißer, bzw. silberfarbener Burg. Dieses wird von zwei aufgerichteten, wegsehenden, goldenen (oder gelben) Löwen gehalten, die auf einem Sockel stehen. Über dem Wappenschild ist ein Helm mit silbern-roter Helmdecke und -wulst, geschmückt mit drei Pfauenfedern und Lanzenfähnchen in Gestalt der Landesflagge dargestellt. Der Helm mit Federschmuck und Fähnlein (ursprünglich ebenfalls weiß mit roter Burg) taucht erstmals im 16. Jahrhundert auf und bildet das mittlere Wappen. Auch das große Wappen einschließlich der schildhaltenden Löwen entstand als Nachahmung fürstlicher Wappen vermutlich spätestens im 16. Jahrhundert. 1695 wird es erstmals auf Münzen verwendet.[12] Die Darstellung des großen Staatswappen wurde zwischen 1952 und 1955 im Zusammenhang mit der Niederschrift der Verfassung der Freien und Hansestadt Hamburg unter Weglassung einiger Details vereinfacht. Die herausgestreckten Zungen der Löwen sind etwas drastischer dargestellt und aus ungeklärten Gründen wurd',
      type: ['land'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Landeswappen',
    }, {
      locationName: 'Großes Staatswappen',
      locationUrl: 'https://de.wikipedia.org/wiki/Landeswappen_Hamburgs#Gro%C3%9Fes_Staatswappen_und_Logo',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Wappen_der_Hamburgischen_B%C3%BCrgerschaft.svg/120px-Wappen_der_Hamburgischen_B%C3%BCrgerschaft.svg.png',
      description: 'Großes Staatswappen |||| Das große Staatswappen darf nur von der Bürgerschaft, vom Senat, dem Hamburgischen Verfassungsgericht, dem Hanseatischen Oberlandesgericht sowie dem Landgericht Hamburg geführt werden. Es zeigt den roten Wappenschild mit weißer, bzw. silberfarbener Burg. Dieses wird von zwei aufgerichteten, wegsehenden, goldenen (oder gelben) Löwen gehalten, die auf einem Sockel stehen. Über dem Wappenschild ist ein Helm mit silbern-roter Helmdecke und -wulst, geschmückt mit drei Pfauenfedern und Lanzenfähnchen in Gestalt der Landesflagge dargestellt. Der Helm mit Federschmuck und Fähnlein (ursprünglich ebenfalls weiß mit roter Burg) taucht erstmals im 16. Jahrhundert auf und bildet das mittlere Wappen. Auch das große Wappen einschließlich der schildhaltenden Löwen entstand als Nachahmung fürstlicher Wappen vermutlich spätestens im 16. Jahrhundert. 1695 wird es erstmals auf Münzen verwendet.[12] Die Darstellung des großen Staatswappen wurde zwischen 1952 und 1955 im Zusammenhang mit der Niederschrift der Verfassung der Freien und Hansestadt Hamburg unter Weglassung einiger Details vereinfacht. Die herausgestreckten Zungen der Löwen sind etwas drastischer dargestellt und aus ungeklärten Gründen wurd',
      type: ['land'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Landeswappen',
    }, {
      locationName: '',
      locationUrl: '',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Wappen-Altona.svg/97px-Wappen-Altona.svg.png',
      description: 'Aktuelles Wappen bzw. Logo',
      type: ['formerBezirke'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Bezirke (auch historische)',
    }, {
      locationName: '',
      locationUrl: '',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/DEU_Altona_COA.svg/105px-DEU_Altona_COA.svg.png',
      description: 'Wappen bis 1937',
      type: ['formerBezirke'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Bezirke (auch historische)',
    }, {
      locationName: '',
      locationUrl: '',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wappen_Hamburg-Altona.png/103px-Wappen_Hamburg-Altona.png',
      description: 'Frühere Variante',
      type: ['formerBezirke'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Bezirke (auch historische)',
    }, {
      locationName: '',
      locationUrl: '',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Fensterbild_mit_Wappen_von_Hamburg_Altona.jpg/108px-Fensterbild_mit_Wappen_von_Hamburg_Altona.jpg',
      description: 'Wappen als Fensterbild',
      type: ['formerBezirke'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Bezirke (auch historische)',
    }, {
      locationName: 'Bergstedt',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Bergstedt',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Wappen_Bergstedt.png/107px-Wappen_Bergstedt.png',
      description: 'Bergstedt',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Bramfeld',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Bramfeld',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Wappen_Bramfeld.png/120px-Wappen_Bramfeld.png',
      description: '↑ Bramfelds Wappen. Stadtteilarchiv Bramfeld, abgerufen am 22. März 2024. |||| Bramfeld[3]',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Eidelstedt',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Eidelstedt#Wappen',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/de/thumb/e/eb/Wappen_eidelstedt_solo_rgb_trans.png/105px-Wappen_eidelstedt_solo_rgb_trans.png',
      description: 'Eidelstedt |||| Das Eidelstedter Stadtteil-Logo „Wappen für Eidelstedt“ Blasonierung des Eidelstedter Stadtteil-Logos „Wappen für Eidelstedt“: In Gold wurzelt eine schwarzstämmige Doppeleiche mit breiter grüner Laubkrone und siebzehn goldenen Eicheln. Rechts und links von den Wurzeln in Versalien der Wahlspruch UP EWIG UNGEDEELT. Unterer Schild geteilt: links – durch die Schildrundung angeschnitten – in rotem Feld eine silberne dreitürmige Burg mit geschlossenem Tor, über den Turmspitzen ein Kreuz und zwei Sterne (Hamburg Wappen), rechts in blauem Feld eine silberne vierflügelige Holländerwindmühle. Über dem Wappen kann Schwarz und in voller Wappenbreite in Versalien der Schriftzug HAMBURG-EIDELSTEDT stehen. Das Wappen für Eidelstedt wurde in den Jahren 2008 bis 2010 unter Einbeziehung der Eidelstedter Bevölkerung entwickelt. Initiatoren dieses Prozesses waren das Eidelstedter Bürgerhaus, der Eidelstedter Bürgerverein und der Sportverein Eidelstedt. Jeder in Eidelstedt soll die Möglichkeit haben, das Stadtteil-Logo unentgeltlich als Identitätssymbol für seine Zwecke einzusetzen.[9]',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Langenhorn',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Langenhorn',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Coa_hh-langenhorn.svg/100px-Coa_hh-langenhorn.svg.png',
      description: 'Langenhorn',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Lurup',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Lurup',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Wappen_Lurup.png/91px-Wappen_Lurup.png',
      description: '↑ neu.atdotde.de (PDF; 12 MB) |||| Lurup[4]',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Ochsenwerder',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Ochsenwerder',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Wappen_Ochsenwerder.png/98px-Wappen_Ochsenwerder.png',
      description: 'Ochsenwerder',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Ottensen',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Ottensen',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Wappen_Ottensen.png/92px-Wappen_Ottensen.png',
      description: 'Ottensen',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Wellingsbüttel',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Wellingsb%C3%BCttel',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Wappen_Wellingsbuettel.png/108px-Wappen_Wellingsbuettel.png',
      description: 'Wellingsbüttel',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: 'Wilhelmsburg',
      locationUrl: 'https://de.wikipedia.org/wiki/Hamburg-Wilhelmsburg',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Wappen_Hamburg-Wilhelmsburg.png/115px-Wappen_Hamburg-Wilhelmsburg.png',
      description: 'Wilhelmsburg',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg | Stadtteile',
    }, {
      locationName: '',
      locationUrl: '',
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Wappen_Harburg-Wilhelmsburg.png/107px-Wappen_Harburg-Wilhelmsburg.png',
      description: 'Wappen der Stadt Harburg-Wilhelmsburg 1927–1937',
      type: ['city'],
      source: 'https://de.wikipedia.org/wiki/Liste_der_Wappen_in_Hamburg',
      sourceTitle: 'Liste der Wappen in Hamburg',
    }
]; 
