export const locationTitleByHerbTitle = {
  'Herb gminy Czarny Bór': 'Czarny Bór (gmina w powiecie wałbrzyskim)',
  'Herb gminy Rogowo (powiat żniński)': 'Rogowo (powiat żniński)',
  'Rogowo (powiat żniński)': 'Rogowo (powiat żniński)',
  'Herb gminy Zielona Góra': 'Zielona Góra (gmina wiejska)',
  'Herb gminy wiejskiej Brzeziny (województwo łódzkie)': 'Brzeziny_(gmina_wiejska_w_województwie_łódzkim)',
  'Herb gminy Bystra-Sidzina': 'Bystra-Sidzina',
  'Herb gminy Igołomia-Wawrzeńczyce': 'Igołomia-Wawrzeńczyce',
  'Herb gminy Jerzmanowice-Przeginia': 'Jerzmanowice-Przeginia',
  'Herb gminy Kocmyrzów-Luborzyca': 'Kocmyrzów-Luborzyca',
  'Herb gminy Wielka Wieś': 'Wielka Wieś (gmina)',
  'Herb gminy Wiśniowa (województwo małopolskie)': 'Wiśniowa (gmina w województwie małopolskim)',
  'Herb Mszczonowa': 'Mszczonów (gmina)',
  'Herb gminy Osieczna (województwo pomorskie)': 'Osieczna (gmina w województwie pomorskim)',
  'Herb gminy Janów (powiat częstochowski)': 'Janów (województwo śląskie)',
  'Herb Nowego Bytomia': 'Nowy Bytom',
  'Herb gminy Słupia Konecka': 'Słupia Konecka',
  'Herb gminy Brudzew': 'Brudzew (gmina)',
  'Herb gminy Czerwonak': 'Czerwonak (gmina)',
  'Herb gminy Ostrowice': 'Ostrowice (gmina)',
  'Herb gminy Radowo Małe': 'Radowo Małe (gmina)',
  'Herb Margonina': 'Margonin (gmina)',
  'Herb Bielawy': 'Bielawa',
  'Herb Wolina': 'Wolin (miasto)',
  'Herb Szczecina': 'Szczecin',
  'Herb Stargardu': 'Stargard',
  'Herb Żerkowa': 'Żerków_(gmina)',
  'Herb Zbąszynia': 'Zbąszyń',
  'Herb Ujścia': 'Ujście (miasto)',
  'Herb Turku': 'Turek',
  'Herb Poznania': 'Poznań',
  'Herb Piły': 'Piła (miasto)',
  'Herb Żywca': 'Żywiec',
  'Herb Rudy Śląskiej': 'Ruda Śląska',
  'Herb Raciborza': 'Racibórz',
  'Herb Koziegłów': 'Koziegłowy (miasto)',
  'Herb Katowic': 'Katowice',
  'Herb Czeladzi': 'Czeladź (miasto)',
  'Herb Czechowic-Dziedzic': 'Czechowice-Dziedzice',
  'Herb Chorzowa': 'Chorzów',
  'Herb Strumienia': 'Strumień (miasto)',
  'Herb Redy': 'Reda (miasto)',
  'Herb Helu': 'Hel (miasto)',
  'Herb Czarnej Wody': 'Czarna Woda (miasto)',
  'Herb Łomży': 'Łomża',
  'Herb Ujazdu (województwo opolskie)': 'Ujazd (województwo opolskie)',
  'Herb Jawora': 'Jawor (miasto)',
  'Herb Bobrownik': 'Bobrowniki (miasto)',
  'Herb Bydgoszczy': 'Bydgoszcz',
  'Herb Izbicy': 'Izbica (miasto)',
  'Herb Lublina': 'Lublin',
  'Herb Łodzi': 'Łódź',
  'Herb Czarnego Dunajca': 'Czarny Dunajec (miasto)',
  'Herb Krakowa': 'Kraków',
  'Herb Miechowa': 'Miechów',
  'Herb Nowego Sącza': 'Nowy Sącz',
  'Herb Skały': 'Skała (miasto)',
  'Herb Tarnowa': 'Tarnów',
  'Herb Jastrzębia': 'Jastrząb (miasto)',
  'Herb Płocka': 'Płock',
  'Herb Skaryszewa': 'Skaryszew',
  'Herb Szydłowca': 'Szydłowiec',
  'Herb Warszawy': 'Warszawa',
  'Herb Brzegu': 'Brzeg (miasto)',
  'Herb Wisły': 'Wisła (miasto)',
  'Herb Bogorii': 'Bogoria (miasto)',
  'Herb Kutna': 'Kutno',
  'Herb powiatu kłodzkiego': 'Powiat kłodzki',
  'Herb powiatu wałbrzyskiego': 'Powiat wałbrzyski',
  'Herb powiatu łęczyckiego': 'Powiat łęczycki',
  'Herb powiatu bocheńskiego': 'Powiat bocheński',
  'Herb powiatu chrzanowskiego': 'Powiat chrzanowski',
  'Herb powiatu żuromińskiego': 'Powiat żuromiński',
  'Herb powiatu białostockiego': 'Powiat białostocki',
  'Herb powiatu kolneńskiego': 'Powiat kolneński',
  'Herb powiatu siemiatyckiego': 'Powiat siemiatycki',
  'Herb powiatu wejherowskiego': 'Powiat wejherowski',
  'Herb powiatu kazimierskiego': 'Powiat kazimierski',
  'Herb powiatu pińczowskiego': 'Powiat pińczowski',
  'Herb powiatu starachowickiego': 'Powiat starachowicki',
  'Herb powiatu włoszczowskiego': 'Powiat włoszczowski',
  'Herb powiatu elbląskiego': 'Powiat elbląski',
  'Herb powiatu oleckiego': 'Powiat olecki',
  'Herb powiatu hrubieszowskiego': 'Powiat hrubieszowski',
  'Herb powiatu rawskiego': 'Powiat rawski',
} as const;