export const locationTitleByCoatOfArmsTitle = {
  // PL
  'Herb gminy Osieczna (województwo pomorskie)': 'Osieczna (gmina w województwie pomorskim)',
  'Herb gminy Zielona Góra': 'Zielona Góra (gmina wiejska)',
  'Herb powiatu elbląskiego': 'Powiat elbląski',
  'Herb Pilzna': 'Pilzno (Polska)',
  // 'Herb Michałowa': 'Michałowo',
  // 'Herb Otynia': 'Otyń',
  // 'Herb Łodzi': 'Łódź',
  // 'Herb Krakowa': 'Kraków',
  // 'Herb Jastrzębia': 'Jastrząb (miasto)',
  // 'Herb Nowego Miasta nad Pilicą': 'Nowe Miasto nad Pilicą',
  // 'Herb Płocka': 'Płock',
  // 'Herb Warszawy': 'Warszawa',
  // 'Herb Brzegu': 'Brzeg (miasto)',
  // 'Herb Czarnej Wody': 'Czarna Woda (miasto)',
  // 'Herb Helu': 'Hel (miasto)',
  // 'Herb Lubania': 'Lubań (województwo dolnośląskie)',
  // 'Herb Srebrnej Góry': 'Srebrna Góra (województwo dolnośląskie)',
  // 'Herb Dobrzynia nad Wisłą': 'Dobrzyń nad Wisłą',
  // 'Herb Nakła nad Notecią': 'Nakło nad Notecią',
  // 'Herb Józefowa nad Wisłą': 'Józefów nad Wisłą',
  // 'Herb Józefowa (powiat biłgorajski)': 'Józefów (powiat biłgorajski)',
  // 'Herb Kostrzyna nad Odrą': 'Kostrzyn nad Odrą',
  // 'Herb Bolesławca (województwo łódzkie)': 'Bolesławiec (województwo łódzkie)',
  // 'Herb Drzewicy': 'Drzewica (miasto)',
  // 'Herb Ujazdu (województwo łódzkie)': 'Ujazd (powiat tomaszowski)',
  // 'Herb Podgórza': 'Podgórze (Kraków)',
  // 'Herb Czerwińska nad Wisłą': 'Czerwińsk nad Wisłą',
  // 'Herb Józefowa (powiat otwocki)': 'Józefów (powiat otwocki)',
  // 'Herb Nowego Dworu Mazowieckiego': 'Nowy Dwór Mazowiecki',
  // 'Herb Nowego Miasta (powiat płoński)': 'Nowe Miasto (powiat płoński)',
  // 'Herb Wyszogrodu': 'Wyszogród (województwo mazowieckie)',
  // 'Herb Zwolenia (powiat zwoleński)': 'Zwoleń (powiat zwoleński)',
  // 'Herb Jarosławia': 'Jarosław (województwo podkarpackie)',
  // 'Herb Rudnika nad Sanem': 'Rudnik nad Sanem',
  // 'Herb Szczuczyna (województwo podlaskie)': 'Szczuczyn (województwo podlaskie)',
  // 'Herb Nowego Dworu Gdańskiego': 'Nowy Dwór Gdański',
  // 'Herb Olsztyna (województwo śląskie)': 'Olsztyn (województwo śląskie)',
  // 'Herb Sławkowa': 'Sławków (województwo śląskie)',
  // 'Herb Chmielnika': 'Chmielnik (województwo świętokrzyskie)',
  // 'Herb Oleśnicy (województwo świętokrzyskie)': 'Oleśnica (województwo świętokrzyskie)',
  // 'Herb Nowego Miasta Lubawskiego': 'Nowe Miasto Lubawskie',
  // 'Herb Dobrej (powiat turecki)': 'Dobra (powiat turecki)',
  // 'Herb Grabowa nad Prosną': 'Grabów nad Prosną',
  // 'Herb Dobrej (powiat łobeski)': 'Dobra (powiat łobeski)',
  // 'Herb Inowrocławia': 'Inowrocław',
  // 'Herb gminy Czarny Bór': 'Czarny Bór (gmina w powiecie wałbrzyskim)',
  // 'Herb gminy Rogowo (powiat żniński)': 'Rogowo (powiat żniński)',
  // 'Rogowo (powiat żniński)': 'Rogowo (powiat żniński)',
  // 'Herb gminy Zielona Góra': 'Zielona Góra (gmina wiejska)',
  // 'Herb gminy wiejskiej Brzeziny (województwo łódzkie)': 'Brzeziny_(gmina_wiejska_w_województwie_łódzkim)',
  // 'Herb gminy Bystra-Sidzina': 'Bystra-Sidzina',
  // 'Herb gminy Igołomia-Wawrzeńczyce': 'Igołomia-Wawrzeńczyce',
  // 'Herb gminy Jerzmanowice-Przeginia': 'Jerzmanowice-Przeginia',
  // 'Herb gminy Kocmyrzów-Luborzyca': 'Kocmyrzów-Luborzyca',
  // 'Herb gminy Wielka Wieś': 'Wielka Wieś (gmina)',
  // 'Herb gminy Wiśniowa (województwo małopolskie)': 'Wiśniowa (gmina w województwie małopolskim)',
  // 'Herb Mszczonowa': 'Mszczonów (gmina)',
  // 'Herb gminy Osieczna (województwo pomorskie)': 'Osieczna (gmina w województwie pomorskim)',
  // 'Herb gminy Janów (powiat częstochowski)': 'Janów (województwo śląskie)',
  // 'Herb Nowego Bytomia': 'Nowy Bytom',
  // 'Herb gminy Słupia Konecka': 'Słupia Konecka',
  // 'Herb gminy Brudzew': 'Brudzew (gmina)',
  // 'Herb gminy Czerwonak': 'Czerwonak (gmina)',
  // 'Herb gminy Ostrowice': 'Ostrowice (gmina)',
  // 'Herb gminy Radowo Małe': 'Radowo Małe (gmina)',
  // 'Herb Margonina': 'Margonin (gmina)',
  // 'Herb Bielawy': 'Bielawa',
  // 'Herb Wolina': 'Wolin (miasto)',
  // 'Herb Szczecina': 'Szczecin',
  // 'Herb Stargardu': 'Stargard',
  // 'Herb Żerkowa': 'Żerków_(gmina)',
  // 'Herb Zbąszynia': 'Zbąszyń',
  // 'Herb Ujścia': 'Ujście (miasto)',
  // 'Herb Turku': 'Turek',
  // 'Herb Poznania': 'Poznań',
  // 'Herb Piły': 'Piła (miasto)',
  // 'Herb Żywca': 'Żywiec',
  // 'Herb Rudy Śląskiej': 'Ruda Śląska',
  // 'Herb Raciborza': 'Racibórz',
  // 'Herb Koziegłów': 'Koziegłowy (miasto)',
  // 'Herb Katowic': 'Katowice',
  // 'Herb Czeladzi': 'Czeladź (miasto)',
  // 'Herb Czechowic-Dziedzic': 'Czechowice-Dziedzice',
  // 'Herb Chorzowa': 'Chorzów',
  // 'Herb Strumienia': 'Strumień (miasto)',
  // 'Herb Redy': 'Reda (miasto)',
  // 'Herb Łomży': 'Łomża',
  // 'Herb Ujazdu (województwo opolskie)': 'Ujazd (województwo opolskie)',
  // 'Herb Jawora': 'Jawor (miasto)',
  // 'Herb Bobrownik': 'Bobrowniki (miasto)',
  // 'Herb Bydgoszczy': 'Bydgoszcz',
  // 'Herb Izbicy': 'Izbica (miasto)',
  // 'Herb Lublina': 'Lublin',
  // 'Herb Czarnego Dunajca': 'Czarny Dunajec (miasto)',
  // 'Herb Miechowa': 'Miechów',
  // 'Herb Nowego Sącza': 'Nowy Sącz',
  // 'Herb Skały': 'Skała (miasto)',
  // 'Herb Tarnowa': 'Tarnów',
  // 'Herb Skaryszewa': 'Skaryszew',
  // 'Herb Szydłowca': 'Szydłowiec',
  // 'Herb Wisły': 'Wisła (miasto)',
  // 'Herb Bogorii': 'Bogoria (miasto)',
  // 'Herb Kutna': 'Kutno',
  // 'Herb powiatu kłodzkiego': 'Powiat kłodzki',
  // 'Herb powiatu wałbrzyskiego': 'Powiat wałbrzyski',
  // 'Herb powiatu łęczyckiego': 'Powiat łęczycki',
  // 'Herb powiatu bocheńskiego': 'Powiat bocheński',
  // 'Herb powiatu chrzanowskiego': 'Powiat chrzanowski',
  // 'Herb powiatu żuromińskiego': 'Powiat żuromiński',
  // 'Herb powiatu białostockiego': 'Powiat białostocki',
  // 'Herb powiatu kolneńskiego': 'Powiat kolneński',
  // 'Herb powiatu siemiatyckiego': 'Powiat siemiatycki',
  // 'Herb powiatu wejherowskiego': 'Powiat wejherowski',
  // 'Herb powiatu kazimierskiego': 'Powiat kazimierski',
  // 'Herb powiatu pińczowskiego': 'Powiat pińczowski',
  // 'Herb powiatu starachowickiego': 'Powiat starachowicki',
  // 'Herb powiatu włoszczowskiego': 'Powiat włoszczowski',
  // 'Herb powiatu elbląskiego': 'Powiat elbląski',
  // 'Herb powiatu oleckiego': 'Powiat olecki',
  // 'Herb powiatu hrubieszowskiego': 'Powiat hrubieszowski',
  // 'Herb powiatu rawskiego': 'Powiat rawski',
  // 'Herb gminy Wińsko': 'Wińsko (gmina)',
  // 'Herb gminy Radwanice': 'Radwanice (gmina)',
  // - pl
  // et
  'Harjumaa vapp': 'Harju maakond',
  'Pirita linnaosa vapp': 'Pirita', // 'Pirita linnaosa', misses cordinates
  'Maidla valla vapp': 'Maidla vald',
  'Saare valla vapp': 'Saare vald',
  'Järvamaa vapp': 'Järva maakond',
  'Järva valla vapp': 'Järva-Jaani', // 'Järva vald',  misses cordinates
  'Läänemaa vapp': 'Lääne maakond',
  'Ridala valla vapp': 'Ridala vald',
  'Rägavere valla vapp': 'Rägavere vald',
  'Kõlleste valla vapp': 'Kõlleste vald',
  'Laheda valla vapp': 'Laheda vald',
  'Pärnumaa vapp': 'Pärnu maakond',
  'Märjamaa alevi vapp': 'Märjamaa',
  'Saare maakonna vapp': 'Saare maakond',
  'Tartumaa vapp': 'Tartu maakond',
  'Valgamaa vapp': 'Valga maakond',
  'Viljandimaa vapp': 'Viljandi maakond',
  'Abja valla vapp': 'Abja vald',
  'Võrumaa vapp': 'Võru maakond',
  'Setomaa valla vapp': 'Värska',
  'Imavere valla vapp': 'Imavere vald',
  'Kabala valla vapp': 'Türi', // Somone can suggest better
  'Käru valla vapp': 'Käru vald',
  'Lääne-Saare valla vapp': 'Kuressaare', // 'Lääne-Saare vald',
  'Noarootsi valla vapp': 'Noarootsi vald',
  'Piirissaare valla vapp': 'Piirissaare vald',
  'Põdrala valla vapp': 'Põdrala vald',
  'Põhja-Sakala valla vapp': 'Suure-Jaani', // 'Põhja-Sakala vald',
  'Salme valla vapp': 'Salme vald',
  'Tapa valla vapp (2005)': 'Tapa vald (2005)',
  'Torgu valla vapp': 'Torgu vald',
  'Vara valla vapp': 'Vara küla',
  'Vigala valla vapp': 'Vigala vald',
  'Võnnu valla vapp': 'Võnnu vald',
  'Peipsiääre valla vapp': 'Alatskivi', // 'Peipsiääre vald',
  'Õru valla vapp': 'Õru vald',
  'Järvakandi valla vapp': 'Järvakandi',
  'Lääne-Nigula valla vapp': 'Taebla', // 'Lääne-Nigula vald',
  // - et
  // fi
  'Helsingin vaakuna': 'Helsinki',
  'Iitin vaakuna': 'Iitti',
  'Ilmajoen vaakuna': 'Ilmajoki',
  'Isonkyrön vaakuna': 'Isokyrö',
  'Kannuksen vaakuna': 'Kannus (kaupunki)',
  'Lahden vaakuna': 'Lahti',
  'Nokian vaakuna': 'Nokia (kaupunki)',
  'Seinäjoen vaakuna': 'Seinäjoen maalaiskunta', // 'Seinäjoki',
  'Varkauden vaakuna': 'Varkaus (kaupunki)',
  'Turun vaakuna': 'Turun tuomiokirkko',
  'Ylöjärven vaakuna': 'Viljakkala', // 'Ylöjärvi' - it doesn't have cords
  'Vihdin vaakuna': 'Vihti',
  'Kotkan vaakuna': 'Kotka (kaupunki)',
  'Lappeenrannan vaakuna': 'Lappeenranta',
  'Björköbyn vaakuna': 'Björköby (taajama)',
  'Eräjärven vaakuna': 'Orivesi', // 'Eräjärvi', 
  'Haapasaaren vaakuna': 'Kotkansaari',
  'Hiittisten vaakuna': 'Dragsfjärd',
  'Honkajoen vaakuna': 'Kauhanevan–Pohjankankaan kansallispuisto',
  'Hyvinkään maalaiskunnan vaakuna': 'Hyvinkää',
  'Iisalmen maalaiskunnan vaakuna': 'Iisalmi',
  'Kajaanin maalaiskunnan vaakuna': 'Kajaani',
  'Karungin vaakuna': 'Karunki (Suomi)',
  'Karjaan maalaiskunnan vaakuna': 'Karjaa',
  'Koivulahden vaakuna': 'Koivulahti (kylä)',
  'Kuopion maalaiskunnan vaakuna': 'Siilinjärvi',
  'Kuoreveden vaakuna': 'Kuoreveden kirkko',
  'Kymin vaakuna': 'Karhula',
  'Lohjan vaakuna': 'Lohja',
  'Lappeen vaakuna': 'Lauritsala',
  'Maarian vaakuna': 'Rusko',
  'Naantalin maalaiskunnan vaakuna': 'Naantali',
  'Nurmeksen maalaiskunnan vaakuna': 'Nurmes',
  'Pielisjärven vaakuna': 'Pankakoski',
  'Lohjan kunnan vaakuna': 'Lohja',
  'Oulujoen vaakuna': 'Oulujoki (Suomen entinen kunta)',
  'Paraisten maalaiskunnan vaakuna': 'Parainen',
  'Peräseinäjoen vaakuna': 'Peräseinäjoen kirkonkylä',
  'Pihlajaveden vaakuna': 'Pihlajavesi (Suomen entinen kunta)',
  'Pohjaslahden vaakuna': 'Pohjaslahden kirkko',
  'Porin maalaiskunnan vaakuna': 'Pihlava',
  'Porvoon maalaiskunnan vaakuna': 'Porvoo',
  'Pusulan vaakuna': 'Lohja',
  'Rovaniemen maalaiskunnan vaakuna': 'Rovaniemi',
  'Simpeleen vaakuna': 'Simpele (taajama)',
  'Säämingin vaakuna': 'Savonranta', // 'Sääminki',
  'Tammisaaren maalaiskunnan vaakuna': 'Tammisaari',
  'Teerijärven vaakuna': 'Kruunupyy',
  'Valtimon vaakuna': 'Valtimon kirkonkylä',
  'Uudenkaarlepyyn maalaiskunnan vaakuna': 'Uusikaarlepyy',
  'Velkuan vaakuna': 'Palva (Velkua)',
  'Viipurin vaakuna': 'Viipuri',
  'Ylimarkun vaakuna': 'Närpiönjoen vesistö',
  'Äänekosken maalaiskunnan vaakuna': 'Äänekoski',
  'Espoon vaakuna': 'Espoo',
  'Öjan vaakuna': 'Öjanjärvi',
  'Forssan vaakuna': 'Forssa',
  'Hangon vaakuna': 'Hanko',
  'Hyvinkään vaakuna': 'Hyvinkää',
  'Hämeenlinnan vaakuna': 'Hämeenlinnan keskustaajama',
  'Heinolan vaakuna': 'Heinola',
  'Jyväskylän vaakuna': 'Jyväskylä',
  'Järvenpään vaakuna': 'Järvenpää',
  'Kajaanin vaakuna': 'Vuolijoki',
  'Kangasalan vaakuna': 'Kangasala',
  'Karkkilan vaakuna': 'Karkkila',
  'Kauhavan vaakuna': 'Kauhava',
  'Kemin vaakuna': 'Kemi',
  'Keravan vaakuna': 'Kerava',
  'Kouvolan vaakuna': 'Kouvola',
  'Etelä-Pohjanmaan vaakuna': 'Seinäjoen maalaiskunta',
} as const;
