export const locationTitleByCoatOfArmsTitle = {
  // PL
  'Herb Wolina': 'Wolin (wyspa)',
  'Herb gminy Osieczna (województwo pomorskie)': 'Osieczna (gmina w województwie pomorskim)',
  'Herb gminy Zielona Góra': 'Zielona Góra (gmina wiejska)',
  'Herb powiatu elbląskiego': 'Powiat elbląski',
  'Herb Pilzna': 'Pilzno (Polska)',
  'Herb województwa dolnośląskiego': 'Wrocław',
  'Herb województwa kujawsko-pomorskiego': 'Bydgoszcz',
  'Herb województwa lubelskiego': 'Lublin',
  'Herb województwa lubuskiego': 'Gorzów Wielkopolski',
  'Herb województwa łódzkiego': 'Łódź',
  'Herb województwa małopolskiego': 'Kraków',
  'Herb województwa mazowieckiego': 'Warszawa',
  'Herb województwa opolskiego': 'Opole',
  'Województwo podkarpackie': 'Rzeszów',
  'Herb województwa podlaskiego': 'Białystok',
  'Herb województwa pomorskiego': 'Gdańsk',
  'Herb województwa śląskiego': 'Katowice',
  'Herb województwa świętokrzyskiego': 'Kielce',
  'Herb województwa warmińsko-mazurskiego': 'Olsztyn',
  'Herb województwa wielkopolskiego': 'Poznań',
  'Herb województwa zachodniopomorskiego': 'Szczecin',
  'Herb Izbicy': 'Izbica (miasto)',
  'Herb Bydgoszczy': 'Bydgoszcz',
  'Herb Jawora': 'Jawor (miasto)',
  'Herb Kosowa Lackiego': 'Kosów Lacki',
  'Herb Nowego Miasta nad Pilicą': 'Nowe Miasto nad Pilicą',
  'Herb Łodzi': 'Łódź',
  'Herb Jastrzębia': 'Jastrząb (miasto)',
  'Herb Szydłowca': 'Szydłowiec',
  'Herb Płocka': 'Płock',
  'Herb Czarnej Wody': 'Czarna Woda (miasto)',
  'Herb Warszawy': 'Warszawa',
  'Herb Katowic': 'Katowice',
  'Herb Czeladzi': 'Czeladź (miasto)',
  'Herb Koziegłów': 'Koziegłowy (miasto)',
  'Herb Raciborza': 'Racibórz',
  'Herb Helu': 'Hel (miasto)',
  'Herb Rudy Śląskiej': 'Ruda Śląska',
  'Herb Wisły': 'Wisła (miasto)',
  'Herb Żywca': 'Żywiec',
  'Herb Poznania': 'Poznań',
  'Herb Ujścia': 'Ujście (miasto)',
  'Herb Szczecina': 'Szczecin',
  'Herb Bobrownik': 'Bobrowniki (gmina w województwie kujawsko-pomorskim)',
  'Herb gminy wiejskiej Brzeziny (województwo łódzkie)': 'Brzeziny (gmina wiejska w województwie łódzkim)',
  'Herb gminy Chynów': 'Chynów (gmina)',
  'Herb gminy Wiśniowa (województwo małopolskie)': 'Wiśniowa (gmina w województwie małopolskim)',
  'Herb gminy Siemiątkowo': 'Siemiątkowo (gmina)',
  'Herb gminy Janów (powiat częstochowski)': 'Janów (gmina w województwie śląskim)',
  'Herb powiatu kazimierskiego': 'Powiat kazimierski',
  'Herb powiatu pińczowskiego': 'Powiat pińczowski',
  'Herb powiatu wałbrzyskiego': 'Wałbrzych',
  'Herb powiatu hrubieszowskiego': 'Powiat hrubieszowski',
  'Herb powiatu bocheńskiego': 'Powiat bocheński',
  'Herb powiatu starachowickiego': 'Powiat starachowicki',
  'Herb powiatu włoszczowskiego': 'Powiat włoszczowski',
  'Herb powiatu oleckiego': 'Powiat olecki',
  'Herb Piły': 'Piła (miasto)',
  'Herb Turku': 'Turek',
  // - pl
  // et
  'Harjumaa vapp': 'Harju maakond',
  'Pirita linnaosa vapp': 'Pirita', // 'Pirita linnaosa', misses cordinates
  'Maidla valla vapp': 'Maidla vald',
  'Saare valla vapp': 'Saare vald',
  'Järvamaa vapp': 'Järva maakond',
  'Järva valla vapp': 'Järva-Jaani', // 'Järva vald',  misses cordinates
  'Läänemaa vapp': 'Lääne maakond',
  'Ridala valla vapp': 'Ridala vald',
  'Rägavere valla vapp': 'Rägavere vald',
  'Kõlleste valla vapp': 'Kõlleste vald',
  'Laheda valla vapp': 'Laheda vald',
  'Pärnumaa vapp': 'Pärnu maakond',
  'Märjamaa alevi vapp': 'Märjamaa',
  'Saare maakonna vapp': 'Saare maakond',
  'Tartumaa vapp': 'Tartu maakond',
  'Valgamaa vapp': 'Valga maakond',
  'Viljandimaa vapp': 'Viljandi maakond',
  'Abja valla vapp': 'Abja vald',
  'Võrumaa vapp': 'Võru maakond',
  'Setomaa valla vapp': 'Värska',
  'Imavere valla vapp': 'Imavere vald',
  'Kabala valla vapp': 'Türi', // Somone can suggest better
  'Käru valla vapp': 'Käru vald',
  'Lääne-Saare valla vapp': 'Kuressaare', // 'Lääne-Saare vald',
  'Noarootsi valla vapp': 'Noarootsi vald',
  'Piirissaare valla vapp': 'Piirissaare vald',
  'Põdrala valla vapp': 'Põdrala vald',
  'Põhja-Sakala valla vapp': 'Suure-Jaani', // 'Põhja-Sakala vald',
  'Salme valla vapp': 'Salme vald',
  'Tapa valla vapp (2005)': 'Tapa vald (2005)',
  'Torgu valla vapp': 'Torgu vald',
  'Vara valla vapp': 'Vara küla',
  'Vigala valla vapp': 'Vigala vald',
  'Võnnu valla vapp': 'Võnnu vald',
  'Peipsiääre valla vapp': 'Alatskivi', // 'Peipsiääre vald',
  'Õru valla vapp': 'Õru vald',
  'Järvakandi valla vapp': 'Järvakandi',
  'Lääne-Nigula valla vapp': 'Taebla', // 'Lääne-Nigula vald',
  'Tudulinna valla vapp': 'Tudulinna vald',
  // - et
  // fi
  'Helsingin vaakuna': 'Helsinki',
  'Iitin vaakuna': 'Iitti',
  'Ilmajoen vaakuna': 'Ilmajoki',
  'Isonkyrön vaakuna': 'Isokyrö',
  'Kannuksen vaakuna': 'Kannus (kaupunki)',
  'Lahden vaakuna': 'Lahti',
  'Nokian vaakuna': 'Nokia (kaupunki)',
  'Seinäjoen vaakuna': 'Seinäjoen maalaiskunta', // 'Seinäjoki',
  'Varkauden vaakuna': 'Varkaus (kaupunki)',
  'Turun vaakuna': 'Turun tuomiokirkko',
  'Ylöjärven vaakuna': 'Viljakkala', // 'Ylöjärvi' - it doesn't have cords
  'Vihdin vaakuna': 'Vihti',
  'Kotkan vaakuna': 'Kotka (kaupunki)',
  'Lappeenrannan vaakuna': 'Lappeenranta',
  'Björköbyn vaakuna': 'Björköby (taajama)',
  'Eräjärven vaakuna': 'Orivesi', // 'Eräjärvi', 
  'Haapasaaren vaakuna': 'Kotkansaari',
  'Hiittisten vaakuna': 'Dragsfjärd',
  'Honkajoen vaakuna': 'Kauhanevan–Pohjankankaan kansallispuisto',
  'Hyvinkään maalaiskunnan vaakuna': 'Hyvinkää',
  'Iisalmen maalaiskunnan vaakuna': 'Iisalmi',
  'Kajaanin maalaiskunnan vaakuna': 'Kajaani',
  'Karungin vaakuna': 'Karunki (Suomi)',
  'Karjaan maalaiskunnan vaakuna': 'Karjaa',
  'Koivulahden vaakuna': 'Koivulahti (kylä)',
  'Kuopion maalaiskunnan vaakuna': 'Siilinjärvi',
  'Kuoreveden vaakuna': 'Kuoreveden kirkko',
  'Kymin vaakuna': 'Karhula',
  'Lohjan vaakuna': 'Lohja',
  'Lappeen vaakuna': 'Lauritsala',
  'Maarian vaakuna': 'Rusko',
  'Naantalin maalaiskunnan vaakuna': 'Naantali',
  'Nurmeksen maalaiskunnan vaakuna': 'Nurmes',
  'Pielisjärven vaakuna': 'Pankakoski',
  'Lohjan kunnan vaakuna': 'Lohja',
  'Oulujoen vaakuna': 'Oulujoki (Suomen entinen kunta)',
  'Paraisten maalaiskunnan vaakuna': 'Parainen',
  'Peräseinäjoen vaakuna': 'Peräseinäjoen kirkonkylä',
  'Pihlajaveden vaakuna': 'Pihlajavesi (Suomen entinen kunta)',
  'Pohjaslahden vaakuna': 'Pohjaslahden kirkko',
  'Porin maalaiskunnan vaakuna': 'Pihlava',
  'Porvoon maalaiskunnan vaakuna': 'Porvoo',
  'Pusulan vaakuna': 'Lohja',
  'Rovaniemen maalaiskunnan vaakuna': 'Rovaniemi',
  'Simpeleen vaakuna': 'Simpele (taajama)',
  'Säämingin vaakuna': 'Savonranta', // 'Sääminki',
  'Tammisaaren maalaiskunnan vaakuna': 'Tammisaari',
  'Teerijärven vaakuna': 'Kruunupyy',
  'Valtimon vaakuna': 'Valtimon kirkonkylä',
  'Uudenkaarlepyyn maalaiskunnan vaakuna': 'Uusikaarlepyy',
  'Velkuan vaakuna': 'Palva (Velkua)',
  'Viipurin vaakuna': 'Viipuri',
  'Ylimarkun vaakuna': 'Närpiönjoen vesistö',
  'Äänekosken maalaiskunnan vaakuna': 'Äänekoski',
  'Espoon vaakuna': 'Espoo',
  'Öjan vaakuna': 'Öjanjärvi',
  'Forssan vaakuna': 'Forssa',
  'Hangon vaakuna': 'Hanko',
  'Hyvinkään vaakuna': 'Hyvinkää',
  'Hämeenlinnan vaakuna': 'Hämeenlinnan keskustaajama',
  'Heinolan vaakuna': 'Heinola',
  'Jyväskylän vaakuna': 'Jyväskylä',
  'Järvenpään vaakuna': 'Järvenpää',
  'Kajaanin vaakuna': 'Vuolijoki',
  'Kangasalan vaakuna': 'Kangasala',
  'Karkkilan vaakuna': 'Karkkila',
  'Kauhavan vaakuna': 'Kauhava',
  'Kemin vaakuna': 'Kemi',
  'Keravan vaakuna': 'Kerava',
  'Kouvolan vaakuna': 'Kouvola',
  'Etelä-Pohjanmaan vaakuna': 'Seinäjoen maalaiskunta',
  'Anjalan vaakuna': 'Anjalan kartano',
  'Vanajan vaakuna': 'Vanaja (Suomen entinen kunta)',
} as const;

export const locationTitleByImages = {
  // DE
  'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Wappen_Landkreis_Heilbronn_alt.svg/108px-Wappen_Landkreis_Heilbronn_alt.svg.png': 'Landkreis Heilbronn',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/DEU_Schwaebisch_Gmuend_COA.svg/93px-DEU_Schwaebisch_Gmuend_COA.svg.png': 'Schwäbisch Gmünd',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/DEU_Lichtenau_COA.svg/46px-DEU_Lichtenau_COA.svg.png': 'Lichtenau (Mittelfranken)',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/DEU_Neunkirchen_am_Sand_COA.svg/46px-DEU_Neunkirchen_am_Sand_COA.svg.png': 'Neunkirchen am Sand',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Wappen_Landkreis_Herzberg.jpg/120px-Wappen_Landkreis_Herzberg.jpg': 'Herzberg (Elster)',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/DEU_Hamburg_COA.svg/86px-DEU_Hamburg_COA.svg.png': 'Hamburg',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Coat_of_arms_of_Hesse.svg/99px-Coat_of_arms_of_Hesse.svg.png': 'Hessen',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Coat_of_arms_of_Mecklenburg-Western_Pomerania_%28great%29.svg/139px-Coat_of_arms_of_Mecklenburg-Western_Pomerania_%28great%29.svg.png': 'Mecklenburg-Vorpommern',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Coat_of_arms_of_North_Rhine-Westphalia.svg/104px-Coat_of_arms_of_North_Rhine-Westphalia.svg.png': 'Nordrhein-Westfalen',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Wappen_des_Saarlands.svg/97px-Wappen_des_Saarlands.svg.png': 'Saarland',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Wappen_Sachsen-Anhalt.svg/99px-Wappen_Sachsen-Anhalt.svg.png': 'Sachsen-Anhalt',
  // DK
  'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Coat_of_arms_of_Holb%C3%A6k_County.svg/98px-Coat_of_arms_of_Holb%C3%A6k_County.svg.png': 'Orø Sogn',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Coat_of_arms_of_Frederiksborg_County.svg/111px-Coat_of_arms_of_Frederiksborg_County.svg.png': 'Region Hovedstaden',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Coat_of_arms_of_Maribo_County.svg/111px-Coat_of_arms_of_Maribo_County.svg.png"': 'Storstrøms Amt',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Coat_of_arms_of_Randers_County.svg/96px-Coat_of_arms_of_Randers_County.svg.png': 'Århus Amt',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Coat_of_arms_of_Hj%C3%B8rring_County.svg/113px-Coat_of_arms_of_Hj%C3%B8rring_County.svg.png': 'Nordjyllands Amt',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Coat_of_arms_of_Ringk%C3%B8bing_County.svg/100px-Coat_of_arms_of_Ringk%C3%B8bing_County.svg.png': 'Vestjylland',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Coat_of_arms_of_Copenhagen_County.svg/100px-Coat_of_arms_of_Copenhagen_County.svg.png': 'Københavns Amt',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Coat_of_arms_of_Skanderborg_County.svg/111px-Coat_of_arms_of_Skanderborg_County.svg.png': 'Skanderborg',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Coat_of_arms_of_Maribo_County.svg/111px-Coat_of_arms_of_Maribo_County.svg.png': 'Storstrøms Amt',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Coats_of_arms_of_None.svg/100px-Coats_of_arms_of_None.svg.png': 'Sønderjyllands Amt',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Coat_of_arms_of_S%C3%B8nderborg_County.svg/94px-Coat_of_arms_of_S%C3%B8nderborg_County.svg.png': 'Sønderjyllands Amt',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Coat_of_arms_of_Sor%C3%B8_County.svg/108px-Coat_of_arms_of_Sor%C3%B8_County.svg.png': 'Vestsjællands Amt',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Coat_of_arms_of_Svendborg_County.svg/109px-Coat_of_arms_of_Svendborg_County.svg.png': 'Odense Amt',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Coat_of_arms_of_Thisted_County.svg/100px-Coat_of_arms_of_Thisted_County.svg.png': 'Thisted',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Coat_of_arms_of_T%C3%B8nder_County.svg/109px-Coat_of_arms_of_T%C3%B8nder_County.svg.png': 'Tønder',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Coat_of_arms_of_Assens_County_Municipality.svg/110px-Coat_of_arms_of_Assens_County_Municipality.svg.png': 'Assens',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Coat_of_arms_of_the_Faroe_Islands.svg/102px-Coat_of_arms_of_the_Faroe_Islands.svg.png': 'Thorshavn',
  // NO
  'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Oslo_komm.svg/100px-Oslo_komm.svg.png': 'Oslo',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Akershus_v%C3%A5pen.svg/101px-Akershus_v%C3%A5pen.svg.png': 'Akershus',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Troms_v%C3%A5pen.svg/101px-Troms_v%C3%A5pen.svg.png': 'Troms',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Bergen_komm.svg/120px-Bergen_komm.svg.png': 'Bergen',
} as const;
