export const locationTitleByHerbTitle = {
  'Herb gminy Czarny Bór': 'Czarny Bór (gmina w powiecie wałbrzyskim)',
  'Herb gminy Rogowo (powiat żniński)': 'Rogowo (powiat żniński)',
  'Rogowo (powiat żniński)': 'Rogowo (powiat żniński)',
  'Herb gminy Zielona Góra': 'Zielona Góra (gmina wiejska)',
  'Herb gminy wiejskiej Brzeziny (województwo łódzkie)': 'Brzeziny_(gmina_wiejska_w_województwie_łódzkim)',
  'Herb gminy Bystra-Sidzina': 'Bystra-Sidzina',
  'Herb gminy Igołomia-Wawrzeńczyce': 'Igołomia-Wawrzeńczyce',
  'Herb gminy Jerzmanowice-Przeginia': 'Jerzmanowice-Przeginia',
  'Herb gminy Kocmyrzów-Luborzyca': 'Kocmyrzów-Luborzyca',
  'Herb gminy Wielka Wieś': 'Wielka Wieś (gmina)',
  'Herb gminy Wiśniowa (województwo małopolskie)': 'Wiśniowa (gmina w województwie małopolskim)',
  'Herb Mszczonowa': 'Mszczonów (gmina)',
  'Herb gminy Osieczna (województwo pomorskie)': 'Osieczna (gmina w województwie pomorskim)',
  'Herb gminy Janów (powiat częstochowski)': 'Janów (województwo śląskie)',
  'Herb Nowego Bytomia': 'Nowy Bytom',
  'Herb gminy Słupia Konecka': 'Słupia Konecka',
  'Herb gminy Brudzew': 'Brudzew (gmina)',
  'Herb gminy Czerwonak': 'Czerwonak (gmina)',
  'Herb gminy Ostrowice': 'Ostrowice (gmina)',
  'Herb gminy Radowo Małe': 'Radowo Małe (gmina)',
  'Herb Margonina': 'Margonin (gmina)',
} as const;